spring.application.name=WhiteBoard-Collabration


# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/collaborative_board?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12Anas34

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:MySuperSecretKeyForCollaborativeWhiteboardProject2024!}